### ISSUE TITLE
Scrapping/Accessing public profile from LinkedIn

### ISSUE THREAD

**Issue by deepanshu-rawat6** [upes-open/OSoC-bio.lnk#6]

**Comment by vasanthanb** [comment]
I think I can work on this issue need a little discription

**Comment by deepanshu-rawat6** [comment]
Hey @vasanthanb , please find the required fields under Integration Platforms [here](https://www.canva.com/design/DAFpEyMnh_Y/LDuNkbwHxOeIBLuQEXfuyA/edit?utm_content=DAFpEyMnh_Y&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

You can use open source APIs or if none works then we have to move on scrapping. Also, this works for all the three issue related to scrapping.

**Comment by deepanshu-rawat6** [comment]
If you find it feasible then I can surely assign you these issues

**Comment by rohin079** [comment]
Web scraping LinkedIn for user data is not possible due to LinkedIn's strict data access policies and measures they have in place to prevent unauthorized scraping. LinkedIn actively detects and blocks automated bots or scrapers that attempt to access their data without permission.

LinkedIn has an API that allows authorized developers to access certain data from their platform. However, this API has limitations and is typically intended for specific use cases, such as integrating LinkedIn features into a website or application, and not for bulk data extraction or scraping.

If you have the LinkedIn username/profile link of the user, you can display their LinkedIn icon or other details by using their public LinkedIn profile URL. You can use this URL to create a link or an icon on your website or application that directs users to the respective LinkedIn profiles.

**Comment by deepanshu-rawat6** [comment]
Yeah @rohin079 , this also sounds good, you can proceed with this approach, and I'll be assigning you this issue
